# Generated by Django 4.0.4 on 2022-10-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='img',
            field=models.CharField(blank=True, default='none', max_length=512),
        ),
    ]
