# Generated by Django 4.1.3 on 2022-11-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_bid_auction'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='close',
            field=models.BooleanField(default=False),
        ),
    ]
