# Generated by Django 4.0.4 on 2023-02-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auction_close'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='img',
            field=models.ImageField(upload_to='files/covers'),
        ),
    ]
