# Generated by Django 4.0.4 on 2023-02-27 19:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_auction_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='auctions/files/auctionImg'),
            preserve_default=False,
        ),
    ]
